/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef hrana_CONSTANTS_H
#define hrana_CONSTANTS_H

#include "hrana_types.h"

namespace hrana { namespace thrift {

class hranaConstants {
 public:
  hranaConstants();

};

extern const hranaConstants g_hrana_constants;

}} // namespace

#endif
