/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef hrana_TYPES_H
#define hrana_TYPES_H

#include <Thrift.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>



namespace hrana { namespace thrift {

enum ResultCode {
  OK,
  TRY_LATER
};

}} // namespace

#endif
