/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "hrana_constants.h"

namespace hrana { namespace thrift {

const hranaConstants g_hrana_constants;

hranaConstants::hranaConstants() {
}

}} // namespace

